version: "3.9"
services:
    femtic-dev:
        build:
            context: .
            dockerfile: ./Dockerfile
        tty: true
        stdin_open: true
        command: /bin/bash
        volumes:
            - .:/usr:rw
